//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace gcs.FishColoring.ConstantVariable
{
	public class FishConstance
	{
		public const string PNG_FORMAT = ".png";
		public const string FISH_AMETHYST_ANIM_LEFT = "fish_amethyst_left";
		public const string FISH_AMETHYST_ANIM_RIGHT = "fish_amethyst_right";
		public const string AMETHYST_ANIM_DIRECTION = "IsDirection";
		public const string ASSEST_RESOURCES_NEW_FISH_PATH = "Assets/Resources/NewFishPath/";
		public const string ASSEST_RESOURCES_OLD_FISH_PATH = "Assets/Resources/OldFishPath/";
		public const string ASSEST_RESOURCES_EXPORT_FISH_PATH = "Assets/Resources/ExportFishPath/";

		public const string FISH_HEAD = "fish_head";
		public const string FISH_BODY = "fish_body";		
		public const string FISH_TAIL = "fish_tail";
		public const string FISH_PELVIC_FIN = "fish_pelvic_fin";
		public const string FISH_DORSAL_FIN = "fish_dorsal_fin";
		public const string FISH_EYE_ONE = "fish_eye_one";
		public const string FISH_EYE_TWO = "fish_eye_two";

		public const int ANIM_BASE_LAYER = 0;

		public const int WELCOME_SCENE =0;
		public const int CAMERA_SCENE =1;
		public const int MAIN_SCENE = 2;
		public const int NUMBER_FISH = 20;

		// Define TAG
		public const string SMALL_IMG_TAG = "SMALL_IMG_TAG";
		public const string FISH_TAG = "FISH_TAG";
	}
}

